from . import help
from . import Fotiha_handler
from . import baqara_handler
from .import imron_handler
from . import niso_handler
from . import maida_handler
from . import anam_hendler
from . import arof_handler
from . import anfol_handler
from . import tavba_handler
from . import yunus_handler
from . import hud_handler
from . import yusuf_handler
from . import rad_handler
from . import ibrohim_handler
from . import hijr_handler
from . import nahl_handler
from . import isro_handler
from . import kahf_handler
from . import maryam_handler
from . import toha_handler
from . import anbiyo_handler
from . import haj_handler
from . import muminun_handler
from . import nur_handler
from . import furqon_handler
from . import shuaro_handler
from . import naml_handler
from . import qasos_handler
from . import ankabut_handler
from . import rum_handler
from . import luqmon_handler
from . import sajda_keybord
from . import ahzob_hendler
from . import saba_handler
from . import fotir_handler
from . import yosin_handler
from . import soffat_handler
from . import sod_handler
from . import zumar_handler
from . import gofir_handler
from . import fussilat_handler
from . import shoro_handler
from . import zuxruf_handler
from . import zuhan_handler
from . import jathiya_handler
from . import ahqaf_handler
from . import muhammad_handler
from . import fath_handler
from . import hujurat_handler
from . import qof_handler
from . import zuriyat_handler
from . import tur_handler
from . import najim_handler
from . import qamar_handler
from . import rohman_handler
from . import voqiya_handler
from . import hadid_handler
from . import mujadila_handler
from . import hashir_handler
from . import mumtahina_handler
from . import soff_handler
from . import juma_handler
from . import munofiqun_handler
from . import taghabun_handler
from . import taloq_handler
from . import taqrim_handler
from . import mulk_handler
from . import qalam_handler
from . import haqqa_handler
from . import muorij_handler
from . import nuh_handler
from . import jinn_handler
from . import muazzamil_handler
from . import muddathir_handler
from . import qiyama_handler
from . import insan_handler
from . import mursalat_handler
from . import naba_handler
from . import naziat_handler
from . import abasa_handler
from . import takavir_handler
from . import infitar_handler
from . import mutaffifeen_handler
from . import inshiqaq_handler
from . import burooj_handler
from . import tariq_handler
from . import ala_handler
from . import ghashiya_handler
from . import fajir_handler
from . import balad_handler
from . import shams_handler
from . import lail_handler
from . import dhuha_handler
from . import sharh_handler
from . import teen_handler
from . import alaq_handler
from . import qadr_handler
from . import bayyina_handler
from . import zilzila_handler
from . import adiyat_handler
from . import qaria_handler
from . import takathur_handler
from . import asr_handler
from . import hamza_handler
from . import fil_handler
from . import quraysh_handler
from . import moun_handler
from . import kavsar_handler
from . import kofirun_handler
from . import nosr_handler
from . import masad_handler
from . import ixlos_handler
from . import falaq_handler
from . import nos_handler
from . import back_handler
from . import namoz_vaqtlari
from . import start
from . import echo