from . import callback_data
from . import Fotiha_keybord
from . import baqara_keybord
from . import imron_keybord
from . import niso_keybord
from . import maida_keybord
from . import anam_keybord
from . import arof_keybord
from . import tavba_keybord
from . import yunus_keybord
from . import hud_keybord
from . import yusuf_keybord
from . import rad_keybord
from . import ibrohim_keybord
from . import hijr_keybord
from . import nahl_keybord
from . import isro_keybord
from . import maryam_keybord
from . import toha_keybord
from . import anbiyo_keybord
from . import haj_keybord
from . import muminun_keybord
from . import nur_keybord
from . import shuaro_keybord
from . import naml_keybord
from . import qasos_keybord
from . import ankabut_keybord
from . import rum_keybord
from . import luqmon_keybord
from . import sajda_keybord
from . import ahzob_keybord
from . import saba_keybord
from . import fotir_keybord
from . import yosin_keybord
from . import soffat_keybord
from . import sod_keybord
from . import zumar_keybord
from . import gofir_keybord
from . import fussilat_keybord
from . import shoro_keybord
from . import zuxruf_keybord
from . import zuhan_keybord
from . import jathiya_keybord
from . import ahqaf_keybord
from . import muhammad_keybord
from . import fath_keybord
from . import hujurat_keybord
from . import qof_keybord
from . import zuriyat_keybord
from . import tur_keybord
from . import najim_keybord
from . import qamar_keybord
from . import rohman_keybord
from . import voqiya_keybord
from . import hadid_keybord
from . import mujadila_keybord
from . import hashir_keybord
from . import mumtahina_keybord
from . import soff_keybord
from . import juma_keybord
from . import munofiqun_keybord
from . import taghabun_keybord
from . import taloq_keybord
from . import taqrim_keybord
from . import mulk_keybord
from . import qalam_keybord
from . import haqqa_keybord
from . import muorij_keybord
from . import nuh_keybord
from . import jinn_keybord
from . import muazzamil_keybord
from . import muddathir_keybord
from . import qiyama_keybord
from . import insan_keybord
from . import mursalat_keybord
from . import naba_keybord
from . import naziat_keybord
from . import abasa_keybord
from . import takavir_keybord
from . import infitar_keybord
from . import mutaffifeen_keybord
from . import inshiqaq_keybord
from . import burooj_keybord
from . import tariq_keybord
from . import ala_keybord
from . import ghashiya_keybord
from . import fajir_keybord
from . import balad_keybord
from . import shams_keybord
from . import lail_keybord
from . import dhuha_keybord
from . import sharh_keybord
from . import teen_keybord
from . import alaq_keybord
from . import qadr_keybord
from . import bayyina_keybord
from . import zilzila_keybord
from . import adiyat_keybord
from . import qaria_keybord
from . import takathur_keybord
from . import asr_keybord
from . import hamza_keybord
from . import fil_keybord
from . import quraysh_keybord
from . import moun_keybord
from . import kavsar_keybord
from . import kofirun_keybord
from . import nosr_keybord
from . import masad_keybord
from . import ixlos_keybord
from . import falaq_keybord
from . import nos_keybord
from . import namoz_vaqtlari_keybord
